# Generated by Django 4.2.7 on 2023-12-01 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='fechapub')),
                ('cuerpo', models.TextField()),
                ('fechapub', models.DateTimeField(default=django.utils.timezone.now)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_blog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fechapub',),
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
