# Generated by Django 4.2.7 on 2023-12-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('ISBN', models.CharField(default='978-1548476434', max_length=14, unique=True)),
                ('edicion', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ('-ISBN',),
            },
        ),
    ]
